FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PIP_INDEX_URL=https://pypi.tuna.tsinghua.edu.cn/simple \
    PIP_TRUSTED_HOST=pypi.tuna.tsinghua.edu.cn

WORKDIR /scripts

RUN pip install --no-cache-dir pymysql bcrypt

COPY init-mysql.py /scripts/init-mysql.py

CMD ["python", "/scripts/init-mysql.py"]
